ipfsImage:
  repo: ipfs/go-ipfs
  tag: v0.27.0

ipfsClusterImage:
  repo: ipfs/ipfs-cluster
  tag: v1.0.8

#### secretes examples #####
#https://cluster.ipfs.io/documentation/guides/k8s/

#od  -vN 32 -An -tx1 /dev/urandom | tr -d ' \n'
clusterSecret: 977be7188a86d0f431760ef25b0734a621a8e1dd697380daf0daebc0d162c56d

#go get github.com/whyrusleeping/ipfs-key
#ipfs-key --type Ed25519 | base64
bootstrapPeerPrivateKey: CAESQKlZsSkQpuQBckidLmnnsR/Wz/wFq/4HIPEUq+t1wxi9mIF2INgIv0sYAdn9ZqUN8hgDTqC2e+1PAVVcU6K5ip8=
bootstrapPeerId: 12D3KooWL5gdo9EBTvSYEPB6kCiPQdpt3Z83m7FEiPXCkoEMmLjp

clusterRestApiId: 12D3KooWFpMypz2WsqsXY1Swcfqz1AEkfrCn77D8T2KqE9GjCokt
clusterRestApiPrivateKey: CAESQN70CP4ufnEBkdpA7ndTixx/kP+kBkc/6s0mi6HcM475WSXoo4jo35+Lu0sRgBBZyPRuLonumff6aVn8Ojh+caE=
clusterRestApiBasicAuth: "ipfs:ipfs-pass"

clusterCRDTtrustedPeers: "12D3KooWNYut1XL31b4KUnCZmC8Mu7WqGn6QdwnptGpS5tnhSttR,12D3KooWNYut1XL31b4KUnCZmC8Mu7WqGn6QdwnptGpS5tnhSttR"
##################

replicaCount: 1

domain: ipfs-cluster.rep.run
httpDomain: ipfs-cluster.rep.run

persistence:
  enabled: true
  clusterStorage: 5Gi
  ipfsStorage: 200Gi
